### ISSUE TITLE
Ist das ein Skript deines (ehem.) Arbeitgebers?

### ISSUE THREAD

**Issue by Plagiat0r** [N3LL4-01/update_tool#1]
Sicher, dass du die Erlaubnis hast, dieses Skript zu veröffentlichen?

Diese Zeile weist darauf hin:
https://github.com/N3LL4-01/update_tool/blob/78c165330d658b1c004a9a2178d2f19cbd93f991/update.sh#L9

Das sieht zum Beispiel nach einer Kundendomain der innomedia AG aus:
https://github.com/N3LL4-01/update_tool/blob/78c165330d658b1c004a9a2178d2f19cbd93f991/update.sh#L28

Und unter https://www.esta-application.com/imprint/ gibt es ein Projekt, bei dem wohl die Tietge GmbH und die innomedia AG zusammengearbeitet haben.

@pyyjac

**Comment by N3LL4-01** [comment]
Ich habe bei Tietge/ innomedia gearbeitet , das Tool war ursprünglich nur für SVN gedacht, da wir komplett auf GIT umgestiegen sind musste ich das Code abändern, der Code selbst hat nichts mehr mit dem ursprünglichen Code zu tun.
